### ISSUE TITLE
Improve introduction

### ISSUE THREAD

**Issue by thomasbach-dev** [tillahoffmann/sphinxcontrib-shtest#7]
Hi there,

this looks very interesting. I am currently have to write some documentation where this could prove incredibly useful. Anyways, I have a hard time getting started. What I did: 
* I installed Sphinx,
* I installed this module by downloading the ZIP provided by GitHub and pointing `pip install` to it,
* I added `"sphinxcontrib.shtest"` to the list vof `extensions` in my `conf.py`,
* I added a couple of examples in my document:

  ``` rst
     .. shtest::

        $ false

     .. shtest::

        $ echo "Hello World!"
        Hello Wolrd!
  ```

Now, I certainly got two nicely formatted boxes in my document with the code above. But, I would have expected an additional failure somewhere, somehow. Am I missing something?

**Comment by tillahoffmann** [comment]
Hey, how did you run the sphinx command? It should look something like

```bash
sphinx-build -b shtest /path/to/source/directory /path/to/output/directory
```

The `-b shtest` is at the bottom of the README and should probably be a bit more prominent.

**Comment by thomasbach-dev** [comment]
Hi @tillahoffmann,

yes, the `-b shtest` was indeed the part I was missing. I noticed that already clarified and explained this much better in the README now. This looks good to me now.

Thanks a lot for publishing this!
